# Generated by Django 5.2.4 on 2025-07-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="static/images/projects/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="skills",
            field=models.ManyToManyField(to="portfolio.skill"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="proficiency",
            field=models.CharField(max_length=50),
        ),
    ]
