# Generated by Django 5.2.4 on 2025-07-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_project_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("link", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="awards/")),
            ],
        ),
        migrations.AddField(
            model_name="experience",
            name="image",
            field=models.ImageField(blank=True, upload_to="experiences/"),
        ),
        migrations.AddField(
            model_name="experience",
            name="link",
            field=models.URLField(blank=True),
        ),
    ]
