# Generated by Django 5.2.4 on 2025-07-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_award_experience_image_experience_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="skills",
            field=models.ManyToManyField(to="portfolio.skill"),
        ),
    ]
